services:
  - type: web
    name: pef-database
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server   # file is src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

